# Generated by Django 4.2.23 on 2025-08-25 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chick_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_type', models.CharField(max_length=25)),
                ('chick_type', models.CharField(choices=[('Broilers', 'Broilers'), ('Layers', 'Layers')], max_length=15)),
                ('chick_breed', models.CharField(choices=[('Local', 'Local'), ('Exotic', 'Exotic')], max_length=15)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chick_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('chick_type', models.CharField(choices=[('Broilers', 'Broilers'), ('Layers', 'Layers')], max_length=15)),
                ('chick_breed', models.CharField(choices=[('local', 'Local'), ('exotic', 'Exotic')], max_length=15)),
                ('chick_price', models.PositiveIntegerField(default=1650)),
                ('chick_quantity', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('registered_by', models.CharField(max_length=50)),
                ('chicks_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('farmer_nin', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('recommender_name', models.TextField()),
                ('recommender_nin', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('recommender_tel', models.CharField(max_length=15)),
                ('farmer_type', models.CharField(choices=[('Starter', 'Starter'), ('Returning', 'Returning')], max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('brooder_manager', 'Brooder Manager'), ('sales_rep', 'Sales Rep')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feed_bags_eligible', models.PositiveIntegerField(default=2)),
                ('feed_payment_due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chick_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.chick_request')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app2.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='chick_request',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.farmer'),
        ),
    ]
