# Generated by Django 4.2.23 on 2025-08-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_type', models.CharField(choices=[('Starter', 'Starter'), ('Returning', 'Returning')], max_length=10)),
                ('chick_type', models.CharField(choices=[('Broilers', 'Broilers'), ('Layers', 'Layers')], max_length=15)),
                ('chick_breed', models.CharField(choices=[('local', 'Local'), ('exotic', 'Exotic')], max_length=15)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('chick_period', models.PositiveIntegerField(default=0)),
                ('took_feeds', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=10)),
                ('delivered', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially paid', 'Partially Paid')], default='pending', max_length=15)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='ChickStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('chick_type', models.CharField(choices=[('Broilers', 'Broilers'), ('Layers', 'Layers')], max_length=15)),
                ('chick_breed', models.CharField(choices=[('local', 'Local'), ('exotic', 'Exotic')], max_length=15)),
                ('chick_price', models.PositiveIntegerField(default=1650)),
                ('chick_quantity', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('registered_by', models.CharField(max_length=50)),
                ('chicks_period', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feed_type', models.CharField(max_length=25)),
                ('feed_brand', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=15, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feed_bags_eligible', models.PositiveIntegerField(default=2)),
                ('feed_payment_due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chick_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='app2.chickrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app2.farmer')),
            ],
        ),
        migrations.RemoveField(
            model_name='chick_request',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Chick_stock',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='chick_request',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Chick_request',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
